# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# set -Dspring.profiles.active=<dev|sit|int> as JVM argument to run in desired profile
# If no profile is specified explicitly, application will fall back to default profile, which is "local"

logging:
    path: logs
    file: ${logging.path}/web-link-service.log  
    level:
        #ROOT: INFO
        com.xebia.sample: DEBUG
        org.hibernate.SQL: DEBUG
        #com.zaxxer.hikari: DEBUG


spring:
    profiles:
        active: dev
    devtools: 
         restart: 
             exclude: application.log,*.log,*.log.*
    application:
        name: sample-service
    datasource:
        url: jdbc:h2:file:~/test
        driver-class-name: org.h2.Driver
        username: sa
        password: root
    h2:
     console:
      enabled: true
      path: /h2    
    jpa:
        show-sql: true
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
    messages:
        basename: i18n/messages
         
server:
    port: 8090     
    
management:
   endpoints:
       web: 
          exposure:
            include: env,beans
    

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# ===================================================================

application:        
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count,X-info"
        #exposed-headers: "Cache-Control,Content-Type,X-Frame-Options,X-XSS-Protection,strict-transport-security,x-content-security-policy,x-content-type-options,Authorization,Link,X-Total-Count,X-pricing-info,X-pricing-warning,X-pricing-success,X-pricing-error"
        allow-credentials: true
        max-age: 1800
    swagger:
        default-include-pattern: /api/.*
        title: Link Sharing API
        description: Link Sharing API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url: