CREATE TABLE LINK (
ID BIGINT NOT NULL AUTO_INCREMENT, 
CREATED_AT DATETIME(6) NOT NULL,
LAST_MODIFIED_DATE TIMESTAMP, 
FAV_COUNT INTEGER, STATUS BIT, 
TITLE VARCHAR(255), 
URL VARCHAR(255), 
PRIMARY KEY (ID));

CREATE TABLE TAG (
ID BIGINT NOT NULL AUTO_INCREMENT, 
TAG_NAME VARCHAR(255), 
TAG_LINK BIGINT, 
PRIMARY KEY (ID));

ALTER TABLE TAG ADD CONSTRAINT LINK_TAG_FK_CONSTRAINT FOREIGN KEY (TAG_LINK) REFERENCES LINK (ID);